export const R = text=> ({class: ['red-bold'], text});
export const redBold = R;
export const r = text=> ({class: ['red'], text});
export const red = r;
export const G = text=> ({class: ['green-bold'], text});
export const greenBold = G;
export const g = text=> ({class: ['green'], text});
export const green = g;
export const B = text=> ({class: ['blue-bold'], text});
export const blueBold = B;
export const b = text=> ({class: ['blue'], text});
export const blue = b;
export const C = text=> ({class: ['cyan-bold'], text});
export const cyanBold = C;
export const c = text=> ({class: ['cyan'], text});
export const cyan = c;
export const M = text=> ({class: ['magenta-bold'], text});
export const magentaBold = M;
export const m = text=> ({class: ['magenta'], text});
export const magenta = m;
export const Y = text=> ({class: ['yellow-bold'], text});
export const yellowBold = Y;
export const y = text=> ({class: ['yellow'], text});
export const yellow = y;
export const X = text=> ({class: ['white'], text});
export const white = X;
export const x = text=> ({class: ['black'], text});
export const black = x;
export const W = text=> ({class: ['gray-bold'], text});
export const grayBold = W;
export const greyBold = W;
export const w = text=> ({class: ['gray'], text});
export const t = text=> ({class: ['tab'], text});
export const tab = t;
export const gray = w;
export const grey = w;
