env:
  browser: true
  es2021: true
extends: ['plugin:vue/vue3-essential', standard]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - vue-pug
rules:
  semi: [2, 'always']
  no-extra-semi: 2
  no-useless-return: error
  prefer-const: error
